# Generated by Django 6.0.3 on 2026-03-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='email',
            new_name='youremail',
        ),
    ]
