# Generated by Django 6.0.3 on 2026-03-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_email_portfolio_youremail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='youremail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='yourname',
            new_name='name',
        ),
    ]
