# Generated by Django 6.0.3 on 2026-03-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_youremail_portfolio_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
