# Generated by Django 6.0.3 on 2026-03-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_portfolio_message_alter_portfolio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='message',
            field=models.TextField(max_length=200),
        ),
    ]
