# Generated by Django 5.2.12 on 2026-03-24 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_portfolio_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
